"""Emit the intake screen's prepared-case list.

Generated rather than hand-maintained, so the addresses offered on the intake
screen can never drift from the scenarios actually seeded into the cache. A
mismatch there would show a judge an address that traces to nothing.

Called by scripts/build_scenarios.py.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any, List

REPO_ROOT = Path(__file__).resolve().parent.parent

HEADER = """/**
 * Prepared cases for the intake screen.
 *
 * GENERATED by scripts/build_scenarios.py — do not edit by hand.
 *
 * These are prefill values only. Selecting one fills the intake form; the case
 * is then opened and traced through exactly the same code path as an address an
 * investigator types in by hand.
 */

export interface DemoCase {
  slug: string;
  complaintId: string;
  title: string;
  narrative: string;
  demonstrates: string[];
  seedAddress: string;
  chain: 'bitcoin' | 'ethereum';
  provenance: 'live_cached' | 'synthetic_scenario';
}

export const DEMO_CASES: DemoCase[] = [
"""


def _q(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False)


def write_demo_case_list(paths: List[Path]) -> Path:
    target = REPO_ROOT / "frontend" / "src" / "lib" / "demoCases.ts"
    target.parent.mkdir(parents=True, exist_ok=True)

    entries: List[str] = []
    for path in paths:
        document = json.loads(path.read_text(encoding="utf-8"))
        entries.append(
            "  {\n"
            f"    slug: {_q(document['slug'])},\n"
            f"    complaintId: {_q(document['complaint_id'])},\n"
            f"    title: {_q(document['title'])},\n"
            f"    narrative: {_q(document['narrative'])},\n"
            f"    demonstrates: {_q(document['demonstrates'])},\n"
            f"    seedAddress: {_q(document['seed_address'])},\n"
            f"    chain: {_q(document['chain'])},\n"
            f"    provenance: {_q(document['provenance'])},\n"
            "  },"
        )

    target.write_text(HEADER + "\n".join(entries) + "\n];\n", encoding="utf-8")
    return target
