/**
 * Prepared cases for the intake screen.
 *
 * GENERATED by scripts/build_scenarios.py — do not edit by hand.
 *
 * These are prefill values only. Selecting one fills the intake form; the case
 * is then opened and traced through exactly the same code path as an address an
 * investigator types in by hand.
 */

export interface DemoCase {
  slug: string;
  complaintId: string;
  title: string;
  narrative: string;
  demonstrates: string[];
  seedAddress: string;
  chain: 'bitcoin' | 'ethereum';
  provenance: 'live_cached' | 'synthetic_scenario';
}

export const DEMO_CASES: DemoCase[] = [
  {
    slug: "case-a-laundering",
    complaintId: "CYB-2026-00124",
    title: "Layered trail ending at an exchange deposit",
    narrative: "A victim reports losing funds to a fake investment platform. The reported address immediately splits the funds across six fresh addresses, runs one branch through a peel chain, re-aggregates the rest at a single collection address, and deposits to an exchange roughly two hours later.",
    demonstrates: ["rapid fan-out into previously-unseen addresses", "round-number splitting", "peel chain", "timing burst", "fan-in consolidation at an unattributed collector", "attributed cash-out point with a citable public source"],
    seedAddress: "0x8e3da1ee29bb600a230985db56b943df7dc98e70",
    chain: "ethereum",
    provenance: "synthetic_scenario",
  },
  {
    slug: "case-c-bridge-deadend",
    complaintId: "CYB-2026-00131",
    title: "Trail reaching a cross-chain bridge",
    narrative: "The reported address splits funds and moves every branch into a cross-chain bridge contract within minutes. On-chain tracing can follow the money to the bridge and no further — the system reports that boundary rather than inferring a destination on the other side.",
    demonstrates: ["rapid fan-out", "the trail reaching a documented bridge contract", "confidence boundary reported instead of a guessed destination"],
    seedAddress: "0x270bb89e3ce38693e686cea27ffb18f2f010f8b4",
    chain: "ethereum",
    provenance: "synthetic_scenario",
  },
  {
    slug: "case-d-legitimate-consolidation",
    complaintId: "CYB-2026-00140",
    title: "Ordinary exchange deposit consolidation (control case)",
    narrative: "A control case with the same converging shape as a laundering consolidation. Funds leave over days in irregular amounts, the recipients are unrelated to each other, and they all later deposit at the same publicly attributed exchange. The engine checks the convergence, applies its contextual features, and deliberately does not flag it.",
    demonstrates: ["a converging shape that is correctly NOT reported", "fan-in disambiguation via attribution and cluster age", "the suppressed signal shown with its reason, not hidden"],
    seedAddress: "0x1a66219ea1d3d3c30d4fd412e16ed3eedbeef10f",
    chain: "ethereum",
    provenance: "synthetic_scenario",
  },
  {
    slug: "case-e-bitcoin-clustering",
    complaintId: "CYB-2026-00152",
    title: "Bitcoin trail with common-input clustering",
    narrative: "A Bitcoin case where the suspect splits funds across six addresses and later spends five of them together as inputs to a single transaction — revealing common control, and collapsing the visible address set into a much smaller set of actors.",
    demonstrates: ["common-input-ownership clustering", "change-address detection", "the address-to-cluster collapse on a UTXO chain"],
    seedAddress: "bc1qfc8dbc914c2fb25a5b722e24e09baf72c662da",
    chain: "bitcoin",
    provenance: "synthetic_scenario",
  },
];
